#!/bin/bash
################################################################################
#
# Copyright (c) 2017 Intel Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
################################################################################

# auto-generated by tools/update_rosdep_list.sh
# [apt] Installation commands:
  sudo -H apt-get install -y libeigen3-dev
  sudo -H apt-get install -y python3-lxml
  sudo -H apt-get install -y libtinyxml2-dev
  sudo -H apt-get install -y qtbase5-dev
  sudo -H apt-get install -y libfreetype6
  sudo -H apt-get install -y python3-matplotlib
  sudo -H apt-get install -y libfreetype6-dev
  sudo -H apt-get install -y libyaml-dev
  sudo -H apt-get install -y libconsole-bridge-dev
  sudo -H apt-get install -y libcurl4-openssl-dev
  sudo -H apt-get install -y curl
  sudo -H apt-get install -y libxaw7-dev
  sudo -H apt-get install -y libcppunit-dev
  sudo -H apt-get install -y libpcre3-dev
  sudo -H apt-get install -y cmake
  sudo -H apt-get install -y clang-format
  sudo -H apt-get install -y libgl1-mesa-dev
  sudo -H apt-get install -y libglu1-mesa-dev
  sudo -H apt-get install -y python3-lark-parser
  sudo -H apt-get install -y libxml2-utils
  sudo -H apt-get install -y pyqt5-dev
  sudo -H apt-get install -y python3-pyqt5
  sudo -H apt-get install -y python3-pyqt5.qtsvg
  sudo -H apt-get install -y python3-sip-dev
  sudo -H apt-get install -y python3-pygraphviz
  sudo -H apt-get install -y python3-flake8
  sudo -H apt-get install -y pyflakes3
  sudo -H apt-get install -y cppcheck
  sudo -H apt-get install -y libxrandr-dev
  sudo -H apt-get install -y libqt5core5a
  sudo -H apt-get install -y qt5-qmake
  sudo -H apt-get install -y python3-pkg-resources
  sudo -H apt-get install -y python3-psutil
  sudo -H apt-get install -y libopencv-dev
  sudo -H apt-get install -y python3-pydot
  sudo -H apt-get install -y libtinyxml-dev
  sudo -H apt-get install -y python3-yaml
  sudo -H apt-get install -y uncrustify
  sudo -H apt-get install -y tango-icon-theme
  sudo -H apt-get install -y libqt5opengl5
  sudo -H apt-get install -y python3-pep8
  sudo -H apt-get install -y python3-pytest
  sudo -H apt-get install -y openssl
  sudo -H apt-get install -y libqt5widgets5
  sudo -H apt-get install -y libassimp-dev
  sudo -H apt-get install -y libpoco-dev
  sudo -H apt-get install -y pydocstyle
  sudo -H apt-get install -y zlib1g-dev
  sudo -H apt-get install -y python3-empy
  sudo -H apt-get install -y libx11-dev
  sudo -H apt-get install -y libqt5gui5
  sudo -H apt-get install -y liblog4cxx-dev
  sudo -H apt-get install -y python3-setuptools
  sudo -H apt-get install -y python3-numpy
  sudo -H apt-get install -y pkg-config
  sudo -H apt-get install -y python3-catkin-pkg-modules
